# adapted from http://conda.pydata.org/docs/travis.html
language: generic

# build matrices
matrix:
  include:
  - os: linux
    dist: trusty
    env: CONDA_PYTHON_VERSION=2.7
  - os: linux
    dist: trusty
    env: CONDA_PYTHON_VERSION=3.6
  - os: osx
    osx_image: xcode8.3
    env: CONDA_PYTHON_VERSION=2.7
  - os: osx
    osx_image: xcode8.3
    env: CONDA_PYTHON_VERSION=3.6

addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.9
        packages:
         - build-essential
         - openjdk-7-jdk
         - swig
         - libjpeg-dev
         - clang-3.9
         - libc++-dev

before_install:
 # download and install miniconda
 - echo "*************************************************"
 - echo "Building for $TRAVIS_OS_NAME"
 - echo "         for Python $CONDA_PYTHON_VERSION"

install:
 - echo "INSTALL CONDA"

before_script:
 # RDKit
 - echo "BEFORE SCRIPT"

script:
  - echo "SCRIPT"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="clang++-3.9 -std=c++11"   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=clang-3.9 ; fi

