# adapted from http://conda.pydata.org/docs/travis.html
language: generic

dist: trusty

# switch to new infrastructure
sudo: false

# build matrices
matrix:
  include:
   - os: linux
     dist: trusty
     addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-3.9
        packages:
         - build-essential
         - openjdk-7-jdk
         - swig
         - libjpeg-dev
         - clang-3.9
         - libc++-dev
   - os: osx

env:
   - CONDA_PYTHON_VERSION=2.7
   - CONDA_PYTHON_VERSION=3.6

install:
 - echo "INSTALL CONDA"
 - conda install -q numpy pillow pandas # matplotlib
 # install the conda boost packages from the RDKit binstar channel.
 - conda install -q py-boost=1.65.1
 # install eigen from conda-forge
 - conda install -q -c conda-forge eigen

before_script:
 # RDKit
 - echo "BEFORE SCRIPT"
 - echo "Uname: `uname`"
 - echo "PYTHON: $CONDA_PYTHON_VERSION"
 - export RDBASE=`pwd`
 - echo $RDBASE
 - export PYTHONPATH=${RDBASE}
 - export LD_LIBRARY_PATH=${RDBASE}/lib
 - export DYLD_LIBRARY_PATH=${RDBASE}/lib

 - export PYTHON=`which python`
 - echo $PYTHON
 - export PY_PREFIX=`$PYTHON -c "import sys; print(sys.prefix)"`
 - echo $PY_PREFIX
 - export PY_SP_DIR=$PY_PREFIX/lib/python$CONDA_PYTHON_VERSION/site-packages
 - echo $PY_SP_DIR

script:
  - echo "SCRIPT"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX="clang++-3.9 -std=c++11"   ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CC=clang-3.9 ; fi
  - echo "CXX $CXX"
  - echo "CC $CC"